# Generated by Django 4.2.20 on 2026-06-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=200)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bloque', models.CharField(max_length=50)),
                ('pisos', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proyecto')),
            ],
        ),
    ]
