# Generated by Django 6.0.7 on 2026-08-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_habitacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización de la habitación'),
        ),
    ]
